package main

import (
	"fmt"
	"strings"

	"github.com/KrimsN/dnspatch/plugin"
)

const (
	// header marks a file as ours; stale files carrying it are deleted.
	header = "// Code generated by cmd/genplugins; DO NOT EDIT."

	// noneTag turns off every provider and retriever of a build, leaving the
	// ones whose own tag is set, and the kinds whose tag below is set.
	noneTag = "dnspatch_none"

	// allProvidersTag and allRetrieversTag switch a whole kind back on.
	allProvidersTag  = "providers_all"
	allRetrieversTag = "retrievers_all"

	// allNotifiersTag switches on every notifier.
	allNotifiersTag = "notify_all"

	catalogFile = "catalog_gen.go"

	readmeStart = "<!-- plugin-tags:start -->"
	readmeEnd   = "<!-- plugin-tags:end -->"
)

// constraint is the build constraint under which the plugin is compiled in.
// Providers and retrievers are on unless noneTag is set, and a tag of their own
// or of their kind switches one back on. Notifiers are the other way round:
// they pull in the client library of a broker, so they are off unless asked for.
func constraint(p found) string {
	switch p.Kind {
	case plugin.KindNotifier:
		return allNotifiersTag + " || " + p.Name
	case plugin.KindProvider:
		return "!" + noneTag + " || " + allProvidersTag + " || " + p.Name
	default:
		return "!" + noneTag + " || " + allRetrieversTag + " || " + p.Name
	}
}

// fileName is the name of the file in package all that imports the plugin.
func fileName(p found) string {
	return string(p.Kind) + "_" + p.Name + ".go"
}

// renderImport is the file that imports one plugin under its build constraint.
func renderImport(p found) []byte {
	return []byte(fmt.Sprintf("%s\n\n//go:build %s\n\npackage all\n\nimport _ %q\n", header, constraint(p), p.Import))
}

// hint tells the user of a build without the plugin how to get it.
func hint(p found) string {
	if p.Kind == plugin.KindNotifier {
		return fmt.Sprintf("rebuild with the %q or %q build tag, or use the -full image (see \"Building from source\" in README.md)", p.Name, allNotifiersTag)
	}

	return fmt.Sprintf("rebuild with the %q build tag (see \"Building from source\" in README.md)", p.Name)
}

// renderCatalog is the file that declares every plugin to plugin.Default, so
// that a build without one can say what to do about it.
func renderCatalog(plugins []found) []byte {
	var b strings.Builder

	fmt.Fprintf(&b, "%s\n\npackage all\n\nimport \"github.com/KrimsN/dnspatch/plugin\"\n\n", header)
	b.WriteString("// Every plugin of the source tree is declared, whether or not this build\n")
	b.WriteString("// compiled it in: that is what lets a configuration that names a missing one\n")
	b.WriteString("// be told which build tag brings it.\n")
	b.WriteString("func init() {\n")

	for _, p := range plugins {
		fmt.Fprintf(&b, "\tplugin.Default.Declare(plugin.%s, %q, %q)\n", kindConst(p.Kind), p.Name, hint(p))
	}

	b.WriteString("}\n")

	return []byte(b.String())
}

func kindConst(kind plugin.Kind) string {
	switch kind {
	case plugin.KindProvider:
		return "KindProvider"
	case plugin.KindRetriever:
		return "KindRetriever"
	default:
		return "KindNotifier"
	}
}

// renderTable is the table of build tags for the README.
func renderTable(plugins []found) string {
	var b strings.Builder

	b.WriteString("| Type | Kind | Build tag | In a plain build |\n")
	b.WriteString("|------|------|-----------|------------------|\n")

	for _, p := range plugins {
		inPlain := "yes"
		if p.Kind == plugin.KindNotifier {
			inPlain = "no (`" + allNotifiersTag + "` brings it too)"
		}

		fmt.Fprintf(&b, "| `%s` | %s | `%s` | %s |\n", p.Name, p.Kind, p.Name, inPlain)
	}

	return b.String()
}

// replaceTable swaps the text between the markers of the README for table.
func replaceTable(readme, table string) (string, error) {
	start := strings.Index(readme, readmeStart)
	end := strings.Index(readme, readmeEnd)

	if start < 0 || end < start {
		return "", fmt.Errorf("README.md has no %s ... %s block to put the table of build tags in", readmeStart, readmeEnd)
	}

	return readme[:start+len(readmeStart)] + "\n\n" + table + "\n" + readme[end:], nil
}
