// Package all registers the built-in plugins through blank imports, so that a
// single import makes them available to a command.
//
// Which plugins a build gets is decided by build tags. Providers and
// retrievers are all in unless the dnspatch_none tag is set; then a tag named
// after a plugin switches that one back on, and providers_all or retrievers_all
// switches on every provider or every retriever. Notifiers are out unless their own
// tag or notify_all is set, since they pull in the client library of a broker.
// The file that imports each plugin, and the catalog that declares them all to
// the registry, are generated by cmd/genplugins from the plugins/ tree; run
// go generate after adding a plugin.
//
// Library users should import the individual plugin packages they need
// instead, to avoid pulling in the dependencies of the others.
package all
